-- Borrar las tablas
DROP TABLE EQUIPOS CASCADE CONSTRAINTS;
DROP TABLE JUGADORES CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE JUEGOS CASCADE CONSTRAINTS;
DROP TABLE ENFRENTAMIENTOS CASCADE CONSTRAINTS;
DROP TABLE JORNADAS CASCADE CONSTRAINTS;
DROP TABLE COMPETICIONES CASCADE CONSTRAINTS;
DROP TABLE PARTICIPACIONES CASCADE CONSTRAINTS;
DROP TABLE STAFF CASCADE CONSTRAINTS;
DROP TABLE PATROCINADORES CASCADE CONSTRAINTS;
DROP TABLE PATROCINIOS CASCADE CONSTRAINTS;


-- Borrar las secuencias 
DROP SEQUENCE EQUIPOS_SEQ;
DROP SEQUENCE JUGADORES_SEQ;
DROP SEQUENCE USUARIOS_SEQ;
DROP SEQUENCE JUEGOS_SEQ;
DROP SEQUENCE ENFRENTAMIENTOS_SEQ;
DROP SEQUENCE JORNADAS_SEQ;
DROP SEQUENCE COMPETICIONES_SEQ;
DROP SEQUENCE STAFF_SEQ;
DROP SEQUENCE PATROCINADORES_SEQ;

-- Crear secuencias
CREATE SEQUENCE EQUIPOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE JUGADORES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USUARIOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE JUEGOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ENFRENTAMIENTOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE JORNADAS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMPETICIONES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE STAFF_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PATROCINADORES_SEQ START WITH 1 INCREMENT BY 1;


-- EQUIPOS
CREATE TABLE EQUIPOS(
    ID_EQUIPO NUMBER(2) DEFAULT EQUIPOS_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(25),
    FECHA_FUNDACION DATE
);

-- JUGADORES
CREATE TABLE JUGADORES(
    ID_JUGADOR NUMBER(2) DEFAULT JUGADORES_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    NACIONALIDAD VARCHAR2(50),
    FECHA_NACIMIENTO DATE,
    NICKNAME VARCHAR2(50),
    ROL VARCHAR2(50),
    SUELDO NUMBER(10),
    ID_EQUIPO NUMBER(2),
    CONSTRAINT SUELDO_CHK CHECK (SUELDO>1134),
    CONSTRAINT ID_EQUIPO_J_FK FOREIGN KEY (ID_EQUIPO)
        REFERENCES EQUIPOS(ID_EQUIPO)
);

-- USUARIOS
CREATE TABLE USUARIOS(
    ID_USUARIO NUMBER(2) DEFAULT USUARIOS_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    CONTRASENA VARCHAR2(50),
    ROL VARCHAR2(50),
    CONSTRAINT CHK_ROL CHECK(ROL IN('ADMINISTRADOR', 'USUARIO'))
);

-- JUEGOS
CREATE TABLE JUEGOS(
    ID_JUEGO NUMBER(2) DEFAULT JUEGOS_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    EMPRESA VARCHAR2(50),
    FECHA_LANZAMIENTO DATE
);

-- ENFRENTAMIENTOS
CREATE TABLE ENFRENTAMIENTOS(
    ID_ENFRENTAMIENTO NUMBER(2) DEFAULT ENFRENTAMIENTOS_SEQ.NEXTVAL PRIMARY KEY,
    HORA TIMESTAMP,
    ID_JORNADA NUMBER(2),
    ID_EQUIPO_LOCAL NUMBER(2),
    ID_EQUIPO_VISITANTE NUMBER(2),
    ID_GANADOR NUMBER(2),
    CONSTRAINT ID_EQUIPO_LOCAL_FK FOREIGN KEY (ID_EQUIPO_LOCAL)
        REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT ID_EQUIPO_VISITANTE_FK FOREIGN KEY (ID_EQUIPO_VISITANTE)
        REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT ID_GANADOR_FK FOREIGN KEY (ID_GANADOR)
        REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT ID_JORNADA_FK FOREIGN KEY (ID_JORNADA)
        REFERENCES JORNADAS(ID_JORNADA)
);

-- COMPETICIONES
CREATE TABLE COMPETICIONES(
    ID_COMPETICION NUMBER(2) DEFAULT COMPETICIONES_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ESTADO NUMBER(1) CONSTRAINT estado_check CHECK (ESTADO IN (0, 1)),
    ID_JUEGO NUMBER(2),
    CONSTRAINT ID_JUEGO_COM_FK FOREIGN KEY (ID_JUEGO)
        REFERENCES JUEGOS(ID_JUEGO)
);

-- JORNADAS
CREATE TABLE JORNADAS(
    ID_JORNADA NUMBER(3) DEFAULT JORNADAS_SEQ.NEXTVAL PRIMARY KEY,
    N_JORNADA NUMBER(2),
    FECHA_JORNADA DATE,
    ID_COMPETICION NUMBER(2),
    CONSTRAINT ID_COMPETICION_JORNADA_FK FOREIGN KEY (ID_COMPETICION)
        REFERENCES COMPETICIONES(ID_COMPETICION)
);



-- PARTICIPACIONES
CREATE TABLE PARTICIPACIONES(
    ID_EQUIPO NUMBER(2),
    ID_COMPETICION NUMBER(2),
    PUNTUACION VARCHAR2(10),
    CONSTRAINT ID_EQUIPO_PART_PK PRIMARY KEY (ID_EQUIPO, ID_COMPETICION),
    CONSTRAINT ID_EQUIPO_PART_FK FOREIGN KEY (ID_EQUIPO)
        REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT ID_COMPETICION_PART_FK FOREIGN KEY (ID_COMPETICION)
        REFERENCES COMPETICIONES(ID_COMPETICION)
);

-- STAFF
CREATE TABLE STAFF(
    ID_STAFF NUMBER(2) DEFAULT STAFF_SEQ.NEXTVAL PRIMARY KEY,
    PUESTO VARCHAR2(50),
    NOMBRE VARCHAR2(50),
    SUELDO NUMBER(10),
    ID_EQUIPO NUMBER(2),
    CONSTRAINT CHK_PUESTO CHECK(UPPER(PUESTO) IN('ENTRENADOR', 'ASISTENTE')),
    CONSTRAINT ID_EQUIPO_STF_FK FOREIGN KEY (ID_EQUIPO)
        REFERENCES EQUIPOS(ID_EQUIPO)
);

-- PATROCINADORES
CREATE TABLE PATROCINADORES(
    ID_PATROCINADOR NUMBER(2) DEFAULT PATROCINADORES_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(50)
);

-- PATROCINIOS
CREATE TABLE PATROCINIOS(
    ID_PATROCINADOR NUMBER(2),
    ID_EQUIPO NUMBER(2),
    CONSTRAINT ID_PATROCINADOR_FK FOREIGN KEY (ID_PATROCINADOR)
        REFERENCES PATROCINADORES(ID_PATROCINADOR),
    CONSTRAINT ID_EQUIPO_FK FOREIGN KEY (ID_EQUIPO)
        REFERENCES EQUIPOS(ID_EQUIPO)
);

-- vistas
CREATE OR REPLACE VIEW Jugadores_Sin_Equipo AS
SELECT nombre, nickname, rol, sueldo
FROM jugadores
WHERE id_equipo IS NULL;

CREATE OR REPLACE VIEW Staff_Sin_Equipo AS
SELECT nombre, puesto
FROM STAFF
WHERE id_equipo IS NULL;

CREATE OR REPLACE VIEW Todos_Los_Equipos AS
SELECT nombre
FROM EQUIPOS;
