-- Insertar datos en la tabla JUEGOS
INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (JUEGOS_SEQ.NEXTVAL, 'Counter-Strike: Global Offensive', 'Valve Corporation', TO_DATE('21-08-2012', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (JUEGOS_SEQ.NEXTVAL, 'League of Legends', 'Riot Games', TO_DATE('27-10-2009', 'DD-MM-YYYY'));

-- Insertar datos en la tabla COMPETICIONES
INSERT INTO COMPETICIONES (ID_COMPETICION, NOMBRE, FECHA_INICIO, FECHA_FIN, ESTADO, ID_JUEGO)
VALUES (COMPETICIONES_SEQ.NEXTVAL, 'Campeonato Mundial de League of Legends 2024', TO_DATE('01-09-2024', 'DD-MM-YYYY'), TO_DATE('01-10-2024', 'DD-MM-YYYY'), 0, 2);

INSERT INTO COMPETICIONES (ID_COMPETICION, NOMBRE, FECHA_INICIO, FECHA_FIN, ESTADO, ID_JUEGO)
VALUES (COMPETICIONES_SEQ.NEXTVAL, 'ESL One: Rio 2024', TO_DATE('10-11-2024', 'DD-MM-YYYY'), TO_DATE('15-11-2024', 'DD-MM-YYYY'), 0, 1);

-- Insertar datos en la tabla EQUIPOS
INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE, FECHA_FUNDACION)
VALUES (EQUIPOS_SEQ.NEXTVAL, 'Team Liquid', TO_DATE('01-01-2000', 'DD-MM-YYYY'));

INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE, FECHA_FUNDACION)
VALUES (EQUIPOS_SEQ.NEXTVAL, 'Fnatic', TO_DATE('01-01-2001', 'DD-MM-YYYY'));

INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE, FECHA_FUNDACION)
VALUES (EQUIPOS_SEQ.NEXTVAL, 'Cloud9', TO_DATE('01-01-2002', 'DD-MM-YYYY'));

INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE, FECHA_FUNDACION)
VALUES (EQUIPOS_SEQ.NEXTVAL, 'G2 Esports', TO_DATE('01-01-2003', 'DD-MM-YYYY'));

-- Insertar datos en la tabla USUARIOS
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, CONTRASENA, ROL)
VALUES (USUARIOS_SEQ.NEXTVAL, 'admin', 'admin', 'ADMINISTRADOR');

INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, CONTRASENA, ROL)
VALUES (USUARIOS_SEQ.NEXTVAL, 'user1', 'user1', 'USUARIO');

-- Insertar datos en la tabla JUGADORES
INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Michael Grzesiek', 'Canadiense', TO_DATE('02-06-1994', 'DD-MM-YYYY'), 'Shroud', 'Jugador profesional', 10000, 1);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Oleksandr Kostyliev', 'Ruso', TO_DATE('08-10-1997', 'DD-MM-YYYY'), 'S1mple', 'Jugador profesional', 15000, 2);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Johan Sundstein', 'Danes', TO_DATE('08-10-1993', 'DD-MM-YYYY'), 'N0tail', 'Jugador profesional', 12000, 3);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Marcelo David', 'Brasileño', TO_DATE('19-05-1999', 'DD-MM-YYYY'), 'coldzera', 'Jugador profesional', 14000, 4);

-- Insertar jugadores adicionales
-- Equipo 1
INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Tyler Latham', 'Estadounidense', TO_DATE('06-10-1995', 'DD-MM-YYYY'), 'Ninja', 'Jugador profesional', 12000, 1);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Guy Beahm', 'Estadounidense', TO_DATE('10-03-1982', 'DD-MM-YYYY'), 'DrDisRespect', 'Jugador profesional', 13000, 1);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Jaryd Lazar', 'Estadounidense', TO_DATE('23-04-1987', 'DD-MM-YYYY'), 'Summit1G', 'Jugador profesional', 11000, 1);

-- Equipo 2
INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Gabriel Toledo', 'Brasileño', TO_DATE('30-05-1990', 'DD-MM-YYYY'), 'FalleN', 'Jugador profesional', 16000, 2);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Fernando Alvarenga', 'Brasileño', TO_DATE('30-05-1991', 'DD-MM-YYYY'), 'fer', 'Jugador profesional', 15500, 2);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Marcelo David', 'Brasileño', TO_DATE('19-05-1999', 'DD-MM-YYYY'), 'coldzera', 'Jugador profesional', 14000, 2);

-- Equipo 3
INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Johan Sundstein', 'Danes', TO_DATE('08-10-1993', 'DD-MM-YYYY'), 'N0tail', 'Jugador profesional', 12000, 3);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Jesse Vainikka', 'Finlandés', TO_DATE('17-08-1993', 'DD-MM-YYYY'), 'JerAx', 'Jugador profesional', 12500, 3);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Topias Taavitsainen', 'Finlandés', TO_DATE('19-08-1992', 'DD-MM-YYYY'), 'Topson', 'Jugador profesional', 13000, 3);

-- Equipo 4
INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Marcelo David', 'Brasileño', TO_DATE('19-05-1999', 'DD-MM-YYYY'), 'coldzera', 'Jugador profesional', 14000, 4);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Epitacio Pessoa', 'Brasileño', TO_DATE('30-01-1997', 'DD-MM-YYYY'), 'TACO', 'Jugador profesional', 13500, 4);

INSERT INTO JUGADORES (ID_JUGADOR, NOMBRE, NACIONALIDAD, FECHA_NACIMIENTO, NICKNAME, ROL, SUELDO, ID_EQUIPO)
VALUES (JUGADORES_SEQ.NEXTVAL, 'Vito Giuseppe', 'Italiano', TO_DATE('09-07-1995', 'DD-MM-YYYY'), 'kNgV-', 'Jugador profesional', 13000, 4);

-- Insertar datos en la tabla STAFF
INSERT INTO STAFF (ID_STAFF, PUESTO, NOMBRE, SUELDO, ID_EQUIPO)
VALUES (STAFF_SEQ.NEXTVAL, 'Entrenador', 'James Banks', 8000, 1);

INSERT INTO STAFF (ID_STAFF, PUESTO, NOMBRE, SUELDO, ID_EQUIPO)
VALUES (STAFF_SEQ.NEXTVAL, 'Entrenador', 'Alexander "kassad" Trifunovic', 8500, 2);

INSERT INTO STAFF (ID_STAFF, PUESTO, NOMBRE, SUELDO, ID_EQUIPO)
VALUES (STAFF_SEQ.NEXTVAL, 'Entrenador', 'Lee "Zefa" Jae-min', 7800, 3);
INSERT INTO PARTICIPACIONES (ID_COMPETICION, ID_EQUIPO)
SELECT 2, ID_EQUIPO FROM EQUIPOS WHERE ID_EQUIPO IN (1, 2, 3, 4);
INSERT INTO STAFF (ID_STAFF, PUESTO, NOMBRE, SUELDO, ID_EQUIPO)
VALUES (STAFF_SEQ.NEXTVAL, 'Entrenador', 'Wilton "zews" Prado', 8200, 4);

-- Insertar datos en la tabla PATROCINADORES
INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (PATROCINADORES_SEQ.NEXTVAL, 'Intel');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (PATROCINADORES_SEQ.NEXTVAL, 'Monster Energy');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (PATROCINADORES_SEQ.NEXTVAL, 'Razer');

-- Insertar datos en la tabla PATROCINIOS
INSERT INTO PATROCINIOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (1, 1);

INSERT INTO PATROCINIOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (2, 2);

INSERT INTO PATROCINIOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (3, 3);

-- Insertar datos en la tabla PARTICIPACIONES
INSERT INTO PARTICIPACIONES (ID_COMPETICION, ID_EQUIPO)
SELECT 1, ID_EQUIPO FROM EQUIPOS WHERE ID_EQUIPO IN (1, 2, 3, 4);

INSERT INTO PARTICIPACIONES (ID_COMPETICION, ID_EQUIPO)
SELECT 2, ID_EQUIPO FROM EQUIPOS WHERE ID_EQUIPO IN (1, 2, 3, 4);